sonar.projectKey=YsraEstudos_teste-laboratorio
sonar.organization=ysraestudos
sonar.projectName=Teste Laboratório
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.js
sonar.exclusions=src/__tests__/**,node_modules/**,dist/**,public/**
