const PROFILES = Object.assign(Object.create(null), {
  low: Object.freeze({
    geometrySegments: Object.freeze({ x: 96, z: 72 }),
    mapResolution: 128,
    deformationResolution: Object.freeze({ width: 256, height: 192 }),
    childFootprintEnabled: false,
    anisotropy: 1,
    shaderCost: 'low',
    sparkles: false,
    receiveShadow: false,
    ambientParticles: false,
    footstepVfx: false,
    gpuParticles: false,
    maxBrushesPerFrame: 32,
    maxContactEmitters: 0,
  }),
  medium: Object.freeze({
    geometrySegments: Object.freeze({ x: 160, z: 120 }),
    mapResolution: 256,
    deformationResolution: Object.freeze({ width: 384, height: 288 }),
    childFootprintEnabled: false,
    anisotropy: 2,
    shaderCost: 'medium',
    sparkles: false,
    receiveShadow: false,
    ambientParticles: true,
    footstepVfx: true,
    gpuParticles: false,
    maxBrushesPerFrame: 64,
    maxContactEmitters: 2,
  }),
  high: Object.freeze({
    geometrySegments: Object.freeze({ x: 240, z: 180 }),
    mapResolution: 256,
    deformationResolution: Object.freeze({ width: 512, height: 384 }),
    childFootprintEnabled: true,
    anisotropy: 2,
    shaderCost: 'high',
    sparkles: true,
    receiveShadow: true,
    ambientParticles: true,
    footstepVfx: true,
    gpuParticles: false,
    maxBrushesPerFrame: 96,
    maxContactEmitters: 4,
  }),
});

export function getSandQuality(name = 'high') {
  return (Object.hasOwn(PROFILES, name) ? PROFILES[name] : null) || PROFILES.high;
}
